Running distillation with optimizer bf...
/home/l/lorenzo-la/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/l/lorenzo-la/experiments/cluster-sim-1/gp_asymmetric.py", line 18, in <module>
    from gp_plots import plot_optimization_process
  File "/home/l/lorenzo-la/experiments/cluster-sim-1/gp_plots.py", line 34, in <module>
    import pandas as pd
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/l/lorenzo-la/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/apps/free81/python/3.10.2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/apps/free81/python/3.10.2/lib/python3.10/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found
INFO:root:1/1 Generating protocols for swap sequence ()...
INFO:root:The space of asymmetric protocols has size 3
INFO:root:
(1/3) Running: {'t_coh': 360000, 'p_gen': 9.6e-08, 'p_swap': 0.85, 'w0': 0.36, 'protocol': (), 't_trunc': 108000000}
INFO:root:Protocol (),	 r = 0.0

INFO:root:
(2/3) Running: {'t_coh': 360000, 'p_gen': 9.6e-08, 'p_swap': 0.85, 'w0': 0.36, 'protocol': ('d0',), 't_trunc': 108000000}
WARNING:root:The size of zero-padded array, shape=268435456, for the Fourier transform is not big enough. The resulting circular convolution might contaminate the distribution.The deviation is as least 2e-12.
WARNING:root:The size of zero-padded array, shape=268435456, for the Fourier transform is not big enough. The resulting circular convolution might contaminate the distribution.The deviation is as least 3e-13.
WARNING:root:The truncation time only covers 97.81% of the distribution, please increase t_trunc.

INFO:root:Protocol ('d0',),	 r = 0.0

/home/l/lorenzo-la/experiments/cluster-sim-1/gp_asymmetric.py:104: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn((f"Simulation under coverage for {protocol}"
WARNING:root:Simulation under coverage for ('d0',)
Set a (higher) fixed truncation time (--t_trunc)
INFO:root:
(3/3) Running: {'t_coh': 360000, 'p_gen': 9.6e-08, 'p_swap': 0.85, 'w0': 0.36, 'protocol': ('d0', 'd0'), 't_trunc': 108000000}
WARNING:root:The size of zero-padded array, shape=268435456, for the Fourier transform is not big enough. The resulting circular convolution might contaminate the distribution.The deviation is as least 2e-12.
WARNING:root:The size of zero-padded array, shape=268435456, for the Fourier transform is not big enough. The resulting circular convolution might contaminate the distribution.The deviation is as least 3e-13.
WARNING:root:The truncation time only covers 97.81% of the distribution, please increase t_trunc.

WARNING:root:The size of zero-padded array, shape=268435456, for the Fourier transform is not big enough. The resulting circular convolution might contaminate the distribution.The deviation is as least 3e-10.
WARNING:root:The size of zero-padded array, shape=268435456, for the Fourier transform is not big enough. The resulting circular convolution might contaminate the distribution.The deviation is as least 1e-11.
WARNING:root:The truncation time only covers 72.08% of the distribution, please increase t_trunc.

INFO:root:Protocol ('d0', 'd0'),	 r = 0.0

WARNING:root:Simulation under coverage for ('d0', 'd0')
Set a (higher) fixed truncation time (--t_trunc)
INFO:root:
Best results: (np.float64(0.0), ())

real	97m1.395s
user	93m54.546s
sys	1m47.681s
